POST http://localhost:9000/api/v1/user/login
Content-Type: application/json

{
  "name": "羿艳ttat",
  "password": "MOuhX9cPwIxPG58"
}

###
GET http://localhost:9000/api/v1/user/get/50ff985d-88f9-438a-a082-69ddc51c0995
http://localhost:9000/api/v1/user/get&uid=50ff985d-88f9-438a-a082-69ddc51c0995